const fs = require('fs');
const path = require('path');

// Extract the scriptUrl directly from sheets-config.js
const configPath = path.join(__dirname, 'js', 'sheets-config.js');

try {
    const configContent = fs.readFileSync(configPath, 'utf-8');
    const match = configContent.match(/scriptUrl:\s*"([^"]+)"/);

    if (!match || !match[1] || match[1] === "YOUR-SCRIPT-URL") {
        console.error("Could not find a valid scriptUrl in js/sheets-config.js.");
        console.error("Please add your Google Apps Script Web App URL there first.");
        process.exit(1);
    }

    const scriptUrl = match[1];
    console.log(`Using script URL: ${scriptUrl}`);

    const tabs = ['Events', 'Blog', 'Projects', 'Resources', 'Team'];
    const siteData = {};

    async function syncData() {
        try {
            console.log("\nFetching data from Google Sheets...");
            
            for (const tab of tabs) {
                console.log(`Fetching ${tab}...`);
                const url = `${scriptUrl}?sheet=${tab}`;
                const response = await fetch(url);
                
                if (!response.ok) {
                throw new Error(`HTTP Error: ${response.status} on tab ${tab}`);
                }
                
                const data = await response.json();
                
                // Normalization step to ensure clean data matches sheets-sync.js behavior
                siteData[tab.toLowerCase()] = data.map(row => {
                let out = {};
                for (let key in row) {
                    out[key] = typeof row[key] === 'string' ? row[key].trim() : row[key];
                }
                // Convert tags back to arrays for projects
                if (tab === 'Projects' && typeof out.tags === 'string') {
                    out.tags = out.tags ? out.tags.split(',').map(t => t.trim()) : [];
                }
                // Normalize casing for team types
                if (tab === 'Team' && out.type) {
                    out.type = out.type.toLowerCase().trim();
                }
                return out;
                }).filter(row => {
                    // Filter empty rows
                    const titleKey = (tab === 'Team') ? 'name' : 'title';
                    return row[titleKey] && String(row[titleKey]).trim() !== '';
                });
            }
            
            const dataJsPath = path.join(__dirname, 'js', 'data.js');
            const fileContent = `/* \n * ============================================================\n *  AUTO-GENERATED FALLBACK DATA\n *  Generated by sync-to-data.js\n * ============================================================\n */\n\nconst siteData = ${JSON.stringify(siteData, null, 2)};\n\nif (typeof module !== 'undefined' && module.exports) {\n  module.exports = siteData;\n}\n`;
            
            fs.writeFileSync(dataJsPath, fileContent);
            console.log(`\n✅ Successfully synced all data to js/data.js!`);
            console.log("Your website's offline/fallback mode is now fully up to date with Google Sheets.");
            
        } catch (error) {
            console.error("\n❌ Error syncing data:", error.message);
            console.error("Make sure your script limit hasn't been reached and the URL is public.");
        }
    }

    syncData();
} catch (fsError) {
    console.error("Could not read js/sheets-config.js. Are you running this script from the website root directory?");
}
